# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Debkanika Gupta"
title_separator          : "-"
name                     : &name "Debkanika Gupta"
description              : &description "PhD Student at Newcastle University"
url                      : https://debkanikagupta.github.io # the base hostname & protocol for your site e.g. "https://[your GitHub username].github.io" or if you already have some other page hosted on Github then use "https://[your GitHub username].github.io/[Your Repo Name]"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "debkanikagupta/debkanikagupta.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "/files/download.png"
  name             : "Debkanika Gupta"
  pronouns         : "she/her"  
  bio              : "PhD Student"
  location         : #"Earth"
  employer         : "Newcastle University"
  uri              : "https://www.ncl.ac.uk/business/people/profile/gupta-debkanika.html"
  email            : "d.gupta3@newcastle.ac.uk" 

  # Academic websites
  arxiv            : # URL - Update with the correct link to your profile
  googlescholar    : #"https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  impactstory      : # URL
  orcid            : #"http://orcid.org/yourorcidurl"
  semantic         : # URL
  pubmed           : #"https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  researchgate     : "https://www.researchgate.net/profile/Debkanika-Gupta"
  scopus           : # URL

  # Repositories and software development
  bitbucket        : # Username - Update with your username on the site
  codepen          : # Username
  dribbble         : # Username
  github           : # "academicpages"
  kaggle           : # Username  
  stackoverflow    : # User number or user number and name (i.e., use "1" or "1/jeff-atwood")    

  # Social media
  bluesky          : #"bsky.app" # Replace this with you Bluesky username
  facebook         : # Username
  flickr           : # Username
  foursquare       : # Username
  goodreads        : # Username
  google_plus      : # Username
  keybase          : # Username
  instagram        : # Username
  lastfm           : # Username
  linkedin         : "www.linkedin.com/in/debkanika-gupta-8671392a3"
  mastodon         : # URL
  medium           : # URL
  pinterest        : # Username
  soundcloud       : # Username
  steam            : # Username
  telegram         : # URL
  tumblr           : # Username
  twitter          : # Username for X / Twitter
  vine             : # Username
  weibo            : # Username
  wikipedia        : # Username
  xing             : # Username
  youtube          : # Username
  zhihu            : # Username


